title: shoppifyProject
logo: /assets/img/logo.png
description: shoppifyProject разработка сервисов 
show_downloads: false

theme: jekyll-theme-minimal

plugins:
  - jekyll-metrics

jekyll_metrics:
  yandex_metrica_id: 90846444
