title: Shoppify
logo: /assets/img/logo.png
description: Панель для мгновенного создания ботов автопродаж
show_downloads: false
demo_panel: 'https://shoppify.ru'
demo_bot: 'https://t.me/shoppify_demo_bot'
channel: 'https://t.me/+Fct_zR35SX9iYWNi'

theme: jekyll-theme-minimal

